name: Notify Digital Garden

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.GARDEN_DISPATCH_TOKEN }}
          repository: Tarawally/digital-garden
          event-type: docs_updated